### ISSUE TITLE
 01. Data ArgumentError: "programming_languages.csv" is not a valid file

### ISSUE THREAD

**Issue by rleyvasal** [JuliaAcademy/DataScience#17]
Notebook **01. Data** shows the following error when running command C = CSV.read("programming_languages.csv");

ArgumentError: "programming_languages.csv" is not a valid file

Stacktrace:
 [1] CSV.Header(::String, ::Int64, ::Bool, ::Int64, ::Nothing, ::Int64, ::Bool, ::Nothing, ::Nothing, ::Bool, ::Nothing, ::Nothing, ::Array{String,1}, 

Running on:
JuliaPro_v1.5.1-1
Windows 10 Pro 64-bit

**Comment by matrixbot123** [comment]
1.In the above lines when you download the file there is a typo 
`P = download("https://raw.githubusercontent.com/nassarhuda/easy_data/master/programming_languages.csv",
    "programminglanguages.csv")`
Change the "programminglanguages.csv" to "programming_languages.csv"
If the problem is not resolved then try this this should resolve the error
2. Instead of this 'C = CSV.read("programming_languages.csv")' to 'C = CSV.read("programming_languages.csv",DataFrame)'

**Comment by kanak8278** [comment]
This may be happening because the `wget` command was unable to run. Therefore, _programming_language.csv_ was not able to be downloaded. You can use the file downloaded from the `download(URL, filename)` command. And rename the downloaded file to or edit the code to downloaded filename i.e. _programminglanguages.csv_.

**Comment by matrixbot123** [comment]
If your `wget`  is not working and you are on windows you can just go to the internet and find wget.exe and put it in your system32 file that worked fo me @rleyvasal

**Comment by logankilpatrick** [comment]
Updated the notebook. Thanks again all!
